Linkup/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Linkup.Models;
using Linkup.Services.Interfaces;
using Linkup.ViewModels.Profile;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Linkup.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IApplicationUserService applicationUserService;
        private readonly ISkillService skillService;
        private readonly IInterestService interestService;

        public ProfileController(IApplicationUserService applicationUserService,
            ISkillService skillService,
            IInterestService interestService)
        {
            this.applicationUserService = applicationUserService;
            this.skillService = skillService;
            this.interestService = interestService;
        }

        #region General

        [HttpGet]
        public async Task<IActionResult> General()
        {
            var profile = await applicationUserService.GetByEmail(User.Identity.Name);
            var viewModel = new ProfileGeneralViewModel
            {
                Email = profile.Email,
                FirstName = profile.FirstName,
                LastName = profile.LastName,
                Mobile = profile.Mobile,
                Department = profile.Department,
                Team = profile.Team,
                Extension = profile.Extension
            };
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> EditGeneral()
        {
            var profile = await applicationUserService.GetByEmail(User.Identity.Name);
            var viewModel = new ProfileGeneralViewModel
            {
                Email = profile.Email,
                FirstName = profile.FirstName,
                LastName = profile.LastName,
                Mobile = profile.Mobile,
                Department = profile.Department,
                Team = profile.Team,
                Extension = profile.Extension
            };
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditGeneral([Bind("Email,FirstName,LastName,Mobile,Department,Team,Extension")] ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                await applicationUserService.Update(applicationUser);
                return RedirectToAction(nameof(General));
            }
            return RedirectToAction(nameof(EditGeneral));
        }

        #endregion

        #region Skills

        [HttpGet]
        public async Task<IActionResult> Skills()
        {
            var profile = await applicationUserService.GetByEmail(User.Identity.Name);
            var skills = await skillService.GetAll();
            var viewModel = new ProfileSkillsViewModel
            {
                CurrentSkills = profile.Skills.Select(s => new ProfileSkillViewModel
                {
                    Id = s.Id,
                    Skill = s.Name
                }).ToList(),
                Skills = skills.Select(s => new SelectListItem
                {
                    Value = s.Id.ToString(),
                    Text = s.Name
                }).ToList()
            };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddSkill(int selectedSkill)
        {
            await applicationUserService.AddUserSkill(User.Identity.Name, selectedSkill);
            return RedirectToAction(nameof(Skills));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteSkill(int selectedSkill)
        {
            await applicationUserService.DeleteUserSkill(User.Identity.Name, selectedSkill);
            return RedirectToAction(nameof(Skills));
        }

        #endregion

        #region Interests

        [HttpGet]
        public async Task<IActionResult> Interests()
        {
            var profile = await applicationUserService.GetByEmail(User.Identity.Name);
            var interests = await interestService.GetAll();
            var viewModel = new ProfileInterestsViewModel
            {
                CurrentInterests = profile.Interests.Select(i => new ProfileInterestViewModel
                {
                    Id = i.Id,
                    Interest = i.Name
                }).ToList(),
                Interests = interests.Select(i => new SelectListItem
                {
                    Value = i.Id.ToString(),
                    Text = i.Name
                }).ToList()
            };
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddInterest(int selectedInterest)
        {
            await applicationUserService.AddUserInterest(User.Identity.Name, selectedInterest);
            return RedirectToAction(nameof(Interests));
        }

        [HttpPost]
        public async Task<IActionResult> DeleteInterest(int selectedInterest)
        {
            await applicationUserService.DeleteUserInterest(User.Identity.Name, selectedInterest);
            return RedirectToAction(nameof(Interests));
        }

        #endregion
    }
}

Linkup/Controllers/ProjectController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Linkup.Models;
using Linkup.Services.Interfaces;
using Linkup.ViewModels.Project;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace Linkup.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IProjectService projectService;
        private readonly ISkillService skillService;
        private readonly IInterestService interestService;
        private readonly IApplicationUserService applicationUserService;

        public ProjectController(IProjectService projectService,
            ISkillService skillService,
            IInterestService interestService,
            IApplicationUserService applicationUserService)
        {
            this.projectService = projectService;
            this.skillService = skillService;
            this.interestService = interestService;
            this.applicationUserService = applicationUserService;
        }

        [HttpGet]
        public async Task<IActionResult> Initiatives(string filter)
        {
            List<Project> projects = new List<Project>();

            if (string.IsNullOrEmpty(filter))
                projects = await projectService.GetAll();
            else if (filter.ToUpper() == "N")
                projects = await projectService.GetNew();
            else if(filter.ToUpper() == "C")
                projects = await projectService.GetCompleted();
            else if(filter.ToUpper() == "R")
                projects = await projectService.GetRecruting();
            else if(filter.ToUpper() == "I")
                projects = await projectService.GetInProgress();
            else if (filter.ToUpper() == "M")
                projects = await projectService.GetByOwner(User.Identity.Name);

            var model = new ProjectListViewModel
            {
                Projects = new List<ProjectViewModel>()
            };

            foreach (var item in projects)
            {
                var createdBy = await applicationUserService.GetByEmail(item.CreatedBy);
                var project = new ProjectViewModel
                {
                    ProjectId = item.Id,
                    CreatedBy = $"{createdBy.FirstName} {createdBy.LastName}",
                    Description = item.Description,
                    Title = item.Title,
                    DueDate = item.DueDate,
                    Progress = item.Progress,
                    Status = item.Status,
                    NeededSkills = item.NeededSkills.Count
                };

                model.Projects.Add(project);
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProjectCreateViewModel projectViewModel)
        {
            var project = new Project
            {
                Title = projectViewModel.Title,
                Description = projectViewModel.Description,
                DueDate = projectViewModel.DueDate,
                CreatedBy = User.Identity.Name,

            };
            await projectService.Create(project);
            await applicationUserService.AddUserProject(User.Identity.Name, project.Id);
            return RedirectToAction(nameof(AddDetails), new { Id = project.Id });
        }

        [HttpGet]
        public async Task<IActionResult> AddDetails(int id)
        {
            var project = await projectService.GetById(id);

            if (project.CreatedBy != User.Identity.Name)
            {
                return Forbid();
            }

            var skillsList = await skillService.GetAll();
            var interestsList = await interestService.GetAll();

            var model = new ProjectCreateViewModel
            {
                ProjectId = project.Id,
                Title = project.Title,
                Description = project.Description,
                DueDate = project.DueDate,
                CreatedBy = project.CreatedBy,
                SkillsList = skillsList.Select(s => new SelectListItem
                {
                    Value = s.Id.ToString(),
                    Text = s.Name
                }).ToList(),
                NeededSkills = project.NeededSkills.Select(s => new ProjectSkillViewModel
                {
                    Id = s.Id,
                    Skill = s.Name
                }).ToList(),
                InterestList = interestsList.Select(i => new SelectListItem
                {
                    Value = i.Id.ToString(),
                    Text = i.Name
                }).ToList(),
                RelatedInterests = project.RelatedInterests.Select(i => new ProjectInterestViewModel
                {
                    Id = i.Id,
                    Interest = i.Name
                }).ToList()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> AddSkill(int projectId, int selectedSkill)
        {
            await projectService.AddProjectSkill(projectId, selectedSkill);
            return RedirectToAction(nameof(AddDetails), new { Id = projectId });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteSkill(int projectId, int selectedSkill)
        {
            await projectService.DeleteProjectSkill(projectId, selectedSkill);
            return RedirectToAction(nameof(AddDetails), new { Id = projectId });
        }

        [HttpPost]
        public async Task<IActionResult> AddInterest(int projectId, int selectedInterest)
        {
            await projectService.AddProjectInterest(projectId, selectedInterest);
            return RedirectToAction(nameof(AddDetails), new { Id = projectId });
        }

        [HttpPost]
        public async Task<IActionResult> DeleteInterest(int projectId, int selectedInterest)
        {
            await projectService.DeleteProjectInterest(projectId, selectedInterest);
            return RedirectToAction(nameof(AddDetails), new { Id = projectId });
        }
    }
}

Linkup/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Linkup</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link href="~/lib/rangeslider/rangeslider.css" rel="stylesheet" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script defer src="https://use.fontawesome.com/releases/v5.15.1/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.15.1/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>
</head>
<body>
    <div class="wrapper bg-light">
        <!-- Sidebar -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Linkup</h3>
            </div>
            <ul class="list-unstyled components">
                <li>
                    <a href="#profileSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Profile</a>
                    <ul class="collapse list-unstyled" id="profileSubmenu">
                        <li>
                            <a asp-controller="Profile" asp-action="General">General</a>
                        </li>
                        <li>
                            <a asp-controller="Profile" asp-action="Skills">Skills</a>
                        </li>
                        <li>
                            <a asp-controller="Profile" asp-action="Interests">Interests</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#dashboardSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Dashboard</a>
                    <ul class="collapse list-unstyled" id="dashboardSubmenu">
                        <li>
                            <a asp-controller="Project" asp-action="Create">Create Initiative</a>
                        </li>
                        <li>
                            <a asp-controller="Project" asp-action="Initiatives" asp-route-filter="M">My Initiatives</a>
                        </li>
                        <li>
                            <a asp-controller="Project" asp-action="Initiatives" asp-route-filter="">All Initiatives</a>
                        </li>
                        <li>
                            <a asp-controller="Project" asp-action="Initiatives" asp-route-filter="N">New Initiatives</a>
                        </li>
                        <li>
                            <a asp-controller="Project" asp-action="Initiatives" asp-route-filter="R">Recruting Initiatives</a>
                        </li>
                        <li>
                            <a asp-controller="Project" asp-action="Initiatives" asp-route-filter="I">In Progress Initiatives</a>
                        </li>
                        <li>
                            <a asp-controller="Project" asp-action="Initiatives" asp-route-filter="C">Completed Initiatives</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a asp-controller="Home" asp-action="About">About</a>
                </li>
            </ul>
        </nav>
        <!-- Page Content -->
        <div id="content">
            @RenderBody()
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="~/lib/rangeslider/rangeslider.js"></script>
    <script src="~/lib/progressbar/progressbar.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>